# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alex Gough
email:
description: >- # this means to ignore newlines until "baseurl:"
    Alex Gough. I'm a PhD student in cosmology, studying the large scale structure of the universe, dark matter, and statistics. I write about theoretical physics, mathematics, science communication and education, and other things I find interesting.
twitter_username: acwgough
github_username: acwgough
minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
search: true

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax

remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /recent/page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  # - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Alex Gough"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Icon art painting from Charlie Rose. I am a PhD student in cosmology at Newcastle University. I'm interested in cosmology, fundamental physics, education, and science communication. Follow me in other places!"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/acwgough"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/acwgough"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alexandergough/"
    - label: "CV"
      icon: "fas fa-file-pdf"
      url: "http:acwgough.github.io/Alexander_Gough_CV.pdf"


footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/acwgough"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/acwgough"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alexandergough/"

# to enable comments set up disqus account and uncomment this.
# comments:
  # provider: "disqus"
  # disqus:
  #   shortname: "acwgough-github-io"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      mathjax: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      mathjax: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
